-- MySQL Script generated by MySQL Workbench
-- Fri Dec 10 01:31:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_swrpi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_swrpi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_swrpi` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `db_swrpi` ;

-- -----------------------------------------------------
-- Table `db_swrpi`.`auth_rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`auth_rule` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`auth_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`auth_item` (
  `name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `type` SMALLINT NOT NULL,
  `description` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rule_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  `created_at` INT NULL DEFAULT NULL,
  `updated_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`name`),
  INDEX `rule_name` (`rule_name` ASC) VISIBLE,
  INDEX `idx-auth_item-type` (`type` ASC) VISIBLE,
  CONSTRAINT `auth_item_ibfk_1`
    FOREIGN KEY (`rule_name`)
    REFERENCES `db_swrpi`.`auth_rule` (`name`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`auth_assignment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`auth_assignment` (
  `item_name` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `user_id` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `created_at` INT NULL DEFAULT NULL,
  PRIMARY KEY (`item_name`, `user_id`),
  INDEX `idx-auth_assignment-user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `auth_assignment_ibfk_1`
    FOREIGN KEY (`item_name`)
    REFERENCES `db_swrpi`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`auth_item_child`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`auth_item_child` (
  `parent` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `child` VARCHAR(64) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  PRIMARY KEY (`parent`, `child`),
  INDEX `child` (`child` ASC) VISIBLE,
  CONSTRAINT `auth_item_child_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `db_swrpi`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `auth_item_child_ibfk_2`
    FOREIGN KEY (`child`)
    REFERENCES `db_swrpi`.`auth_item` (`name`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`membretes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`membretes` (
  `idmembretes` INT NOT NULL AUTO_INCREMENT,
  `superior_membrete` LONGBLOB NOT NULL,
  `inferior_membrete` LONGBLOB NOT NULL,
  PRIMARY KEY (`idmembretes`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`fechadeproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`fechadeproyecto` (
  `idfechadeproyecto` INT NOT NULL AUTO_INCREMENT,
  `fecha_registro` DATE NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_terminacion` DATE NOT NULL,
  PRIMARY KEY (`idfechadeproyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`periodos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`periodos` (
  `idperiodos` INT NOT NULL AUTO_INCREMENT,
  `fechadeproyecto_idfechadeproyecto` INT NOT NULL,
  PRIMARY KEY (`idperiodos`),
  INDEX `fk_periodos_fechadeproyecto1_idx` (`fechadeproyecto_idfechadeproyecto` ASC) VISIBLE,
  CONSTRAINT `fk_periodos_fechadeproyecto1`
    FOREIGN KEY (`fechadeproyecto_idfechadeproyecto`)
    REFERENCES `db_swrpi`.`fechadeproyecto` (`idfechadeproyecto`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`rol` (
  `idrol` INT NOT NULL AUTO_INCREMENT,
  `tipo_rol` VARCHAR(45) NOT NULL COMMENT '1.Administrador\\\\\\\\\\\\\\\\n2.Lider\\\\\\\\\\\\\\\\n',
  `nivel_rol` VARCHAR(45) NOT NULL COMMENT '1\\\\\\\\\\\\\\\\n2\\\\\\\\\\\\\\\\n',
  PRIMARY KEY (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `auth_key` VARCHAR(128) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_hash` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `password_reset_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `status` SMALLINT NOT NULL DEFAULT '10',
  `created_at` INT NOT NULL,
  `updated_at` INT NOT NULL,
  `verification_token` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `rol_idrol` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` USING BTREE (`username`) VISIBLE,
  UNIQUE INDEX `password_reset_token` (`password_reset_token` ASC) VISIBLE,
  INDEX `fk_user_rol1_idx` (`rol_idrol` ASC) VISIBLE,
  CONSTRAINT `fk_user_rol1`
    FOREIGN KEY (`rol_idrol`)
    REFERENCES `db_swrpi`.`rol` (`idrol`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`proyectosinternos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`proyectosinternos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo_proyecto` VARCHAR(100) NOT NULL,
  `tipo_investigacion_proyecto` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '1. basica\\\\\\\\\\\\\\\\n2.aplicada\\\\\\\\\\\\\\\\n3.desarrollo tecnologico\\\\\\\\\\\\\\\\n4.educativa',
  `area_de_desarrollo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '1.Ciencias Químicas\\\\\\\\\\\\\\\\n2.Ingeniería Industrial, Administrativa y Desarrollo Regional\\\\\\\\\\\\\\\\n3.Ciencias Biológicas\\\\\\\\\\\\\\\\n4.Ciencias de la Educación\\\\\\\\\\\\\\\\n5.Ciencias de la Tierra y del Medio Ambiente\\\\\\\\\\\\\\\\n6.Ciencias del Mar\\\\\\\\\\\\\\\\n7.Ingeniería Eléctrica, Electrónica\\\\\\\\\\\\\\\\n8.Ciencias Agrícolas y Forestales\\\\\\\\\\\\\\\\n9.Ingeniería Química, Bioquímica, Alimentos, Biotecnología\\\\\\\\\\\\\\\\n10.Ingeniería Mecánica, Mecatrónica\\\\\\\\\\\\\\\\n11.Ciencias de los Materiales, Polímeros\\\\\\\\\\\\\\\\n12.Ciencias de la Computación, Sistemas Computacionales, Informática',
  `descripcion_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `duracion_proyecto` VARCHAR(45) NOT NULL COMMENT '1.6meses\\\\\\\\\\\\\\\\n2.12meses',
  `institucion_apoyoeconomico` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '1.TecnmValladolid\\\\\\\\\\\\\\\\ndescribir financiamiento y monto total',
  `resumen_proyecto` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `introduccion_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `estado_arte_proyecto` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `objetivo_general_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `objetivo_especifico_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL,
  `periodos_idperiodos` INT NOT NULL,
  `membretes_idmembretes` INT NOT NULL,
  `impactos_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `metodologia_proyecto` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `vinculacion_sector_proyecto` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `referencias_proyecto` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `lugar_desarrollo_proyecto` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `infraestructura_proyecto` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyectosinternos_periodos1_idx` (`periodos_idperiodos` ASC) VISIBLE,
  INDEX `fk_proyectosinternos_membretes1_idx` (`membretes_idmembretes` ASC) VISIBLE,
  INDEX `fk_proyectosinternos_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectosinternos_membretes1`
    FOREIGN KEY (`membretes_idmembretes`)
    REFERENCES `db_swrpi`.`membretes` (`idmembretes`),
  CONSTRAINT `fk_proyectosinternos_periodos1`
    FOREIGN KEY (`periodos_idperiodos`)
    REFERENCES `db_swrpi`.`periodos` (`idperiodos`),
  CONSTRAINT `fk_proyectosinternos_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_swrpi`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`cronogramadeactividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`cronogramadeactividades` (
  `idcronogramadeactividades` INT NOT NULL AUTO_INCREMENT,
  `actividad` TEXT NOT NULL,
  `fecha_de_realizacion` DATE NOT NULL,
  `entregables` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL,
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`idcronogramadeactividades`),
  INDEX `fk_cronogramadeactividades_proyectosinternos1_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_cronogramadeactividades_proyectosinternos1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`colaborador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`colaborador` (
  `iddocente` INT NOT NULL AUTO_INCREMENT,
  `nombre` TEXT NOT NULL,
  `tiempocompleto` VARCHAR(2) CHARACTER SET 'utf8' NOT NULL COMMENT 'Si, No',
  `nivelSNI` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT 'si\\\\r\\\\nno',
  `perfilpromep` VARCHAR(2) NOT NULL COMMENT 'Si, No',
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`iddocente`),
  INDEX `fk_docente_proyectosinternos1_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_docente_proyectosinternos1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`entregablemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`entregablemeta` (
  `identregablemeta` INT NOT NULL AUTO_INCREMENT,
  `tipo_entregable` VARCHAR(45) NOT NULL COMMENT '1. academico \\\\\\\\\\\\\\\\n2. humano',
  `descripcion` VARCHAR(45) NOT NULL COMMENT 'Integración de alumnos de licenciatura al proyecto\\\\\\\\\\\\\\\\nParticipación de alumnos residentes\\\\\\\\\\\\\\\\nParticipación de estudiantes de servicio social\\\\\\\\\\\\\\\\nParticipación de estudiantes por créditos complementarios\\\\\\\\\\\\\\\\nArtículos científicos en revista arbitrada \\\\\\\\\\\\\\\\nArtículos científicos en revista indizadas\\\\\\\\\\\\\\\\nTesis de maestría a desarrollar (indicar en observaciones nombre del tesista, título y anexar programa de trabajo sintético)\\\\\\\\\\\\\\\\nLibros\\\\\\\\\\\\\\\\nCapítulos de libros\\\\\\\\\\\\\\\\nRegistro de Propiedad Intelectual e Industrial\\\\\\\\\\\\\\\\nPrototipos\\\\\\\\\\\\\\\\nPaquetes tecnológicos\\\\\\\\\\\\\\\\nInformes técnicos a empresas o instituciones\\\\\\\\\\\\\\\\nOtros (especifique)',
  `fecha_entrega` DATE NOT NULL,
  `observacion` VARCHAR(45) NULL DEFAULT NULL,
  `evidencia` VARCHAR(45) NULL DEFAULT NULL COMMENT 'subir documento de evidencia\\\\\\\\\\\\\\\\n(documento)',
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`identregablemeta`),
  INDEX `fk_entregablemeta_proyectosinternos1_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_entregablemeta_proyectosinternos1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`formatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`formatos` (
  `idformatos` INT NOT NULL AUTO_INCREMENT,
  `primer_reporte` TEXT NULL DEFAULT NULL,
  `segundo_reporte` TEXT NULL DEFAULT NULL,
  `tercer_reporte` TEXT NULL DEFAULT NULL,
  `protocolo` TEXT NULL DEFAULT NULL,
  `concentrador` TEXT NULL DEFAULT NULL,
  `registro_plantrabajo` TEXT NULL DEFAULT NULL,
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`idformatos`),
  INDEX `fk_formatos_proyectosinternos1_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_formatos_proyectosinternos1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`gradoacademico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`gradoacademico` (
  `idgradoacademico` INT NOT NULL,
  `nombre_de_grado` VARCHAR(45) NOT NULL,
  `sigla_de_grado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgradoacademico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`licenciaturainvolucrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`licenciaturainvolucrada` (
  `idlicenciaturainvolucrada` INT NOT NULL AUTO_INCREMENT,
  `clave_licenciatura` INT NOT NULL,
  `nombre_licenciatura` VARCHAR(45) NOT NULL COMMENT '1.Administracion\\\\\\\\\\\\\\\\n2.Ambiental\\\\\\\\\\\\\\\\n3.Civil\\\\\\\\\\\\\\\\n4.Gestionempresarial\\\\\\\\\\\\\\\\n5.Industrial\\\\\\\\\\\\\\\\n6.Sistemas',
  PRIMARY KEY (`idlicenciaturainvolucrada`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`lineadeinvestigacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`lineadeinvestigacion` (
  `idlineadeinvestigacion` INT NOT NULL AUTO_INCREMENT,
  `clave_linea` VARCHAR(22) NOT NULL,
  `nombre_linea` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idlineadeinvestigacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `parent` INT NULL DEFAULT NULL,
  `route` VARCHAR(255) NULL DEFAULT NULL,
  `order` INT NULL DEFAULT NULL,
  `data` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `parent` (`parent` ASC) VISIBLE,
  CONSTRAINT `menu_ibfk_1`
    FOREIGN KEY (`parent`)
    REFERENCES `db_swrpi`.`menu` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT NULL DEFAULT NULL,
  PRIMARY KEY (`version`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nombre_perfil` VARCHAR(45) NOT NULL,
  `apellido_perfil` VARCHAR(45) NOT NULL,
  `genero_perfil` VARCHAR(45) NOT NULL COMMENT '1.profesora\\\\\\\\\\\\\\\\n2.profesor',
  `ingenieria_perfil` VARCHAR(45) NOT NULL COMMENT 'sistemas\\\\\\\\\\\\\\\\nambiental\\\\\\\\\\\\\\\\ngestion\\\\\\\\\\\\\\\\nindistrial\\\\\\\\\\\\\\\\ncivil\\\\\\\\\\\\\\\\nadmon',
  `SNI` VARCHAR(2) NOT NULL COMMENT 'nivel de sistema nacional de investigadores ',
  `promep_perfil` VARCHAR(2) NOT NULL,
  `tc_perfil` VARCHAR(2) CHARACTER SET 'utf8' NOT NULL COMMENT 'Si\\\\\\\\\\\\\\\\r\\\\\\\\\\\\\\\\nNo',
  `idgradoacademico` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idperfil`),
  INDEX `fk_perfiles_gradoacademico1_idx` (`idgradoacademico` ASC) VISIBLE,
  INDEX `fk_perfil_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_perfil_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_swrpi`.`user` (`id`),
  CONSTRAINT `fk_perfiles_gradoacademico1`
    FOREIGN KEY (`idgradoacademico`)
    REFERENCES `db_swrpi`.`gradoacademico` (`idgradoacademico`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`proyectosexternos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`proyectosexternos` (
  `idproyectosexternos` INT NOT NULL AUTO_INCREMENT,
  `nombre_proyectos_externos` VARCHAR(45) NOT NULL,
  `evidencia` VARCHAR(45) NULL DEFAULT NULL,
  `observaciones` VARCHAR(45) NULL DEFAULT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`idproyectosexternos`),
  INDEX `fk_proyectosexternos_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectosexternos_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `db_swrpi`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`proyectosinternos_has_licenciaturainvolucrada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`proyectosinternos_has_licenciaturainvolucrada` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `licenciaturainvolucrada_idlicenciaturainvolucrada` INT NOT NULL,
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyectosinternos_has_licenciaturainvolucrada_licenciatu_idx` (`licenciaturainvolucrada_idlicenciaturainvolucrada` ASC) VISIBLE,
  INDEX `fk_proyectosinternos_has_licenciaturainvolucrada_proyectosi_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectosinternos_has_licenciaturainvolucrada_licenciatura1`
    FOREIGN KEY (`licenciaturainvolucrada_idlicenciaturainvolucrada`)
    REFERENCES `db_swrpi`.`licenciaturainvolucrada` (`idlicenciaturainvolucrada`),
  CONSTRAINT `fk_proyectosinternos_has_licenciaturainvolucrada_proyectosint1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`proyectosinternos_has_lineadeinvestigacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`proyectosinternos_has_lineadeinvestigacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `lineadeinvestigacion_idlineadeinvestigacion` INT NOT NULL,
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_proyectosinternos_has_lineadeinvestigacion_lineadeinvest_idx` (`lineadeinvestigacion_idlineadeinvestigacion` ASC) VISIBLE,
  INDEX `fk_proyectosinternos_has_lineadeinvestigacion_proyectosinte_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_proyectosinternos_has_lineadeinvestigacion_lineadeinvestig1`
    FOREIGN KEY (`lineadeinvestigacion_idlineadeinvestigacion`)
    REFERENCES `db_swrpi`.`lineadeinvestigacion` (`idlineadeinvestigacion`),
  CONSTRAINT `fk_proyectosinternos_has_lineadeinvestigacion_proyectosintern1`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `db_swrpi`.`reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_swrpi`.`reportes` (
  `idreportes` INT NOT NULL AUTO_INCREMENT,
  `avance_reporte` INT NOT NULL,
  `actividad_reporte` VARCHAR(45) NOT NULL,
  `anexo_reporte` VARCHAR(45) NOT NULL,
  `conclusion_reporte` VARCHAR(45) NOT NULL,
  `observacion_reporte` VARCHAR(45) NOT NULL,
  `proyectosinternos_id` INT NOT NULL,
  PRIMARY KEY (`idreportes`),
  INDEX `fk_reportes_proyectosinternos2_idx` (`proyectosinternos_id` ASC) VISIBLE,
  CONSTRAINT `fk_reportes_proyectosinternos2`
    FOREIGN KEY (`proyectosinternos_id`)
    REFERENCES `db_swrpi`.`proyectosinternos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
